object _earticles: T_earticles
  Left = 506
  Top = 343
  ActiveControl = UText1
  BorderStyle = bsDialog
  Caption = 'Articles'
  ClientHeight = 379
  ClientWidth = 654
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  OnActivate = FormActivate
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  DesignSize = (
    654
    379)
  PixelsPerInch = 120
  TextHeight = 16
  object GradientNC1: TGradientNC
    Left = 178
    Top = 18
    Width = 476
    Height = 361
    ColorInicial = 14281452
    ColorFinal = clSilver
    Direccio = E
    Align = alRight
  end
  object dMARCA: TUDBLabel
    Left = 190
    Top = 70
    Width = 56
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = 'dMARCA'
    Transparent = True
    NoClick = False
    LinkedControl = dID_MAR
    PassColors = True
    Data.Connection = dm.CG
    Data.Table = 'marques'
    Data.PrimaryKey = 'id'
    Data.SFilterKind = fkProgressive
    Look.FixedRowVAlign = vaTop
    Look.FixedRow = clNavy
    Look.FixedRowHeight = 23
    Look.FixedRowFont.Charset = DEFAULT_CHARSET
    Look.FixedRowFont.Color = clWhite
    Look.FixedRowFont.Height = -12
    Look.FixedRowFont.Name = 'Arial'
    Look.FixedRowFont.Style = []
    Look.Odd = 15002091
    Look.Even = 14673116
    Look.DataRowHeight = 18
    Look.DataFont.Charset = DEFAULT_CHARSET
    Look.DataFont.Color = 10526880
    Look.DataFont.Height = -13
    Look.DataFont.Name = 'Arial'
    Look.DataFont.Style = []
    Look.Border = False
    Look.BorderColor = clBlack
    Look.Focused = 33023
    Look.Selected = clNavy
    Look.BackColor = clBtnFace
    PickStyle = psModalOnePick
    Field = 'DESCR'
    DerivedFields.Strings = (
      'dID_MAR=id'
      'dMARGE_MAR=marge')
    OnShowPickForm = dMARCAShowPickForm
  end
  object dDESCR: TTLabel
    Left = 190
    Top = 110
    Width = 430
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14938354
    Caption = 'DDESCR'
    Transparent = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    NoClick = False
    PassColors = False
    Question = 'Descripci'#243
    QWidth = 350
    LabelCase = ecUpperCase
  end
  object dPREC: TNLabel
    Left = 190
    Top = 190
    Width = 50
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14938354
    Caption = '0,00'
    Transparent = True
    OnChange = dPRECChange
    NoClick = False
    PassColors = False
    Question = 'Preu recomanat'
    Format = '0.00'
    NumType = ntFloat
  end
  object dPBASE: TNLabel
    Left = 190
    Top = 130
    Width = 50
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14938354
    Caption = '0,00'
    Transparent = True
    OnSetInnerCaption = dPBASESetInnerCaption
    NoClick = False
    PassColors = False
    Question = 'Preu base'
    Format = '0.00'
    NumType = ntFloat
  end
  object dPVP: TNLabel
    Left = 190
    Top = 210
    Width = 50
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14413038
    Caption = '0,00'
    Transparent = True
    NoClickMessage = 
      'Preu de venta final. Es calcula depenguent del preu de cost, pre' +
      'u m'#224'xim i preu recomenat. Es pot establir un PVP modificant el p' +
      'reu recomenat siguent major que el preu de cost, o b'#233' escollint ' +
      'un marge adecuat'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    NoClick = True
    PassColors = False
    Format = '0.00'
    NumType = ntFloat
  end
  object dPMIN: TNLabel
    Left = 190
    Top = 170
    Width = 50
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14938354
    Caption = '0,00'
    Transparent = True
    OnChange = dPMINChange
    NoClick = False
    PassColors = False
    Question = 'Preu m'#237'nim'
    Format = '0.00'
    NumType = ntFloat
  end
  object dSTOCK: TBLabel
    Left = 190
    Top = 270
    Width = 50
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14938354
    Transparent = True
    NoClick = False
    PassColors = False
    Value = True
    ColorTrue = clBlack
    ColorFalse = clRed
    BoolAlignment = taLeftJustify
  end
  object dFAMILIA: TUDBLabel
    Left = 190
    Top = 50
    Width = 58
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = 'dFAMILIA'
    Transparent = True
    NoClick = False
    LinkedControl = dID_FAM
    PassColors = True
    Data.Connection = dm.CG
    Data.Table = 'families'
    Data.PrimaryKey = 'id'
    Data.SFilterKind = fkProgressive
    Look.FixedRowVAlign = vaTop
    Look.FixedRow = clNavy
    Look.FixedRowHeight = 23
    Look.FixedRowFont.Charset = DEFAULT_CHARSET
    Look.FixedRowFont.Color = clWhite
    Look.FixedRowFont.Height = -12
    Look.FixedRowFont.Name = 'Arial'
    Look.FixedRowFont.Style = []
    Look.Odd = 15002091
    Look.Even = 14673116
    Look.DataRowHeight = 18
    Look.DataFont.Charset = DEFAULT_CHARSET
    Look.DataFont.Color = 10526880
    Look.DataFont.Height = -13
    Look.DataFont.Name = 'Arial'
    Look.DataFont.Style = []
    Look.Border = False
    Look.BorderColor = clBlack
    Look.Focused = 33023
    Look.Selected = clNavy
    Look.BackColor = clBtnFace
    PickStyle = psModalOnePick
    Field = 'DESCR'
    DerivedFields.Strings = (
      'dID_FAM=id'
      'dID_LIN=id_lin')
    OnShowPickForm = dFAMILIAShowPickForm
  end
  object dPCOST: TNLabel
    Left = 190
    Top = 150
    Width = 50
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14413038
    Caption = '0,00'
    Transparent = True
    NoClickMessage = 'Preu de cost. Preu base * (1 + %IVA d'#39'articles)'
    NoClick = True
    PassColors = False
    Question = 'Preu de cost'
    Format = '0.00'
    NumType = ntFloat
  end
  object dDATA_REGISTRE: TDLabel
    Left = 190
    Top = 290
    Width = 68
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14938354
    Caption = '21/11/2007'
    Transparent = True
    NoClick = False
    PassColors = False
    Date = 39407.612926967590000000
    Format = 'ddddd'
    Question = 'Data de registre'
  end
  object dMARGE: TNLabel
    Left = 190
    Top = 230
    Width = 50
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14938354
    Caption = '0,00 %'
    Transparent = True
    OnChange = dMARGEChange
    NoClick = False
    PassColors = False
    Question = 'Marge (sobre venta)'
    Format = '0.00 %'
    NumType = ntFloat
  end
  object dMARGE_MAR: TNLabel
    Left = 190
    Top = 250
    Width = 50
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14413038
    Caption = '0,00 %'
    Transparent = True
    NoClickMessage = 
      'Marge de marca. Es troba segons la marca. Per canviar els marges' +
      ' de marca, anar a la llista '#39'marques'#39
    OnChange = dMARGE_MARChange
    NoClick = True
    PassColors = False
    Format = '0.00 %'
    NumType = ntFloat
  end
  object dID: TNLabel
    Left = 190
    Top = 30
    Width = 9
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = '0'
    Transparent = True
    NoClickMessage = 
      'Refer'#232'ncia d'#39'article. Si '#233's negativa, significa que ha estat ent' +
      'rat per fora de fitxer'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    NoClick = True
    PassColors = False
    Format = '0'
    NumType = ntInt
  end
  object dLINIA: TTLabel
    Left = 190
    Top = 90
    Width = 57
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = 'DDESCR'
    Transparent = True
    NoClickMessage = 'L'#237'nea d'#39'article. Es troba segons la fam'#237'lia'
    NoClick = True
    LinkedControl = dID_LIN
    PassColors = True
    Question = 'Descripci'#243
    QWidth = 350
    LabelCase = ecUpperCase
  end
  object dID_FAM: TNLabel
    Left = 270
    Top = 50
    Width = 21
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = '  (0)'
    Transparent = True
    NoClickMessage = 'refer'#232'ncia de fam'#237'lia'
    OnChange = dPBASEChange
    OnSetInnerCaption = dID_FAMSetInnerCaption
    NoClick = True
    PassColors = False
    Format = '  (0)'
    NumType = ntFloat
  end
  object dID_MAR: TNLabel
    Left = 270
    Top = 70
    Width = 21
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = '  (0)'
    Transparent = True
    NoClickMessage = 'refer'#232'ncia de marca'
    OnChange = dPBASEChange
    OnSetInnerCaption = dID_MARSetInnerCaption
    NoClick = True
    PassColors = False
    Format = '  (0)'
    NumType = ntFloat
  end
  object dID_LIN: TNLabel
    Left = 270
    Top = 90
    Width = 21
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = '  (0)'
    Transparent = True
    NoClickMessage = 'refer'#232'ncia de l'#237'nia. Es troba mitjan'#231'ant la fam'#237'lia escollida'
    OnChange = dID_LINChange
    OnSetInnerCaption = dID_LINSetInnerCaption
    NoClick = True
    PassColors = False
    Format = '  (0)'
    NumType = ntFloat
  end
  object Shape1: TShape
    Left = 175
    Top = 30
    Width = 1
    Height = 301
    Pen.Color = clSilver
  end
  object dCODI_BARRES: TTLabel
    Left = 190
    Top = 310
    Width = 430
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Color = 14938354
    Transparent = True
    NoClick = False
    PassColors = False
    Question = 'Codi de barres'
    QWidth = 400
    LabelCase = ecNormal
  end
  object UText1: TUText
    Left = 30
    Top = 50
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Familia d'#39'article'
    Caption = '&Fam'#237'lia'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dFAMILIA
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 1
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText2: TUText
    Left = 30
    Top = 70
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Marca d'#39'article'
    Caption = '&Marca'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dMARCA
    OnReact = UText2React
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 2
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object btAnterior: TUText
    Left = 10
    Top = 350
    Width = 111
    Height = 22
    Cursor = crHandPoint
    Alignment = taCenter
    Anchors = [akLeft, akBottom]
    Caption = '&< anterior'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = False
    ReactAndActive = True
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    BorderStyle = sbsSingle
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 15
    TabStop = True
    ParentFont = False
    SelectAndNext = False
    AcceptMouseWheel = True
    PassColor = False
  end
  object btSeguent: TUText
    Left = 120
    Top = 350
    Width = 111
    Height = 22
    Cursor = crHandPoint
    Alignment = taCenter
    Anchors = [akLeft, akBottom]
    Caption = 'seg'#252'ent &>'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = False
    ReactAndActive = True
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    BorderStyle = sbsSingle
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 16
    TabStop = True
    ParentFont = False
    SelectAndNext = False
    AcceptMouseWheel = True
    PassColor = False
  end
  object btEntrar: TUText
    Left = 532
    Top = 350
    Width = 111
    Height = 22
    Cursor = crHandPoint
    Alignment = taCenter
    Anchors = [akRight, akBottom]
    Caption = '&Entrar'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    BorderStyle = sbsSingle
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 17
    TabStop = True
    ParentFont = False
    SelectAndNext = False
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText4: TUText
    Left = 30
    Top = 110
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Descripci'#243' d'#39'article'
    Caption = 'Des&cripci'#243
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dDESCR
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 4
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText5: TUText
    Left = 30
    Top = 170
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Preu m'#237'nim'
    Caption = 'Preu m'#237'&nim'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dPMIN
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 7
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText6: TUText
    Left = 30
    Top = 190
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Preu recomanat'
    Caption = 'Preu &recomenat'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dPREC
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 8
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText7: TUText
    Left = 30
    Top = 130
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Preu base de compra'
    Caption = 'Preu &base'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dPBASE
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 5
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText10: TUText
    Left = 30
    Top = 270
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'En stock'
    Caption = '&Stock'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dSTOCK
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 12
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText3: TUText
    Left = 30
    Top = 290
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Data de registre'
    Caption = '&Data de registre'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dDATA_REGISTRE
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 13
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText8: TUText
    Left = 30
    Top = 230
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 
      'Nom'#233's tindr'#224' efecte cambiar-ho si PCost > PMin,PRec i marge de m' +
      'arca = 0'
    Caption = 'M&arge (sobre PVP)'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dMARGE
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 10
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 654
    Height = 18
    Align = alTop
    BevelOuter = bvNone
    Caption = 'Panel1'
    TabOrder = 18
  end
  object UText9: TUText
    Left = 30
    Top = 30
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Familia d'#39'article'
    Caption = 'Refer'#232'ncia'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dID
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 0
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText11: TUText
    Left = 30
    Top = 90
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Familia d'#39'article'
    Caption = 'L'#237'nia'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dLINIA
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 3
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText12: TUText
    Left = 30
    Top = 150
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Preu base de compra'
    Caption = 'Preu de cost'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dPCOST
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 6
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText13: TUText
    Left = 30
    Top = 210
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Preu base de compra'
    Caption = 'Preu de venta'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dPVP
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 9
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText14: TUText
    Left = 30
    Top = 250
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 
      'Nom'#233's tindr'#224' efecte cambiar-ho si PCost > PMin,PRec i marge de m' +
      'arca = 0'
    Caption = 'Marge de marca'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dMARGE_MAR
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 11
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText15: TUText
    Left = 30
    Top = 310
    Width = 140
    Height = 19
    Cursor = crHandPoint
    Hint = 'Data de registre'
    Caption = 'C&odi de barres'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dCODI_BARRES
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 14
    TabStop = True
    ParentFont = False
    ShowHint = True
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UDBAlterForm: TUDBAlterForm
    NextButton = btSeguent
    PriorButton = btAnterior
    OkButton = btEntrar
    ControlPrefix = 'd'
    NotAllowPost = False
    AfterLoadValues = UDBAlterFormAfterLoadValues
    OnGetNewId = UDBAlterFormGetNewId
    LoadDefValues = UDBAlterFormLoadDefValues
    Messages.ErrorMsg = 'Error actualitzant valors'
    Messages.SaveMsg = 'Guardar canvis?'
    Messages.BadValue = 'Valor '#39'%VALUE%'#39' incorrecte per el camp %FIELD%'
    Messages.DeleteMsg = 'Eliminar registre d'#39'articles #%PRIMARY%. Continuar?'
    Messages.NotAllowPost = 'Posting not allowed'
    PrimaryField = 'id'
    AllowedNilFields = 'id_lin,id_mar,id_fam,data_registre'
    Left = 502
    Top = 108
  end
end
