object _econcepte: T_econcepte
  Left = 446
  Top = 330
  ActiveControl = tCONCEPTE
  BorderStyle = bsDialog
  Caption = 'Concepte'
  ClientHeight = 258
  ClientWidth = 741
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  OnActivate = FormActivate
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  DesignSize = (
    741
    258)
  PixelsPerInch = 120
  TextHeight = 16
  object GradientNC1: TGradientNC
    Left = 160
    Top = 0
    Width = 581
    Height = 258
    ColorInicial = 14281452
    ColorFinal = clSilver
    Direccio = E
    Align = alRight
  end
  object dCONCEPTE_DESCR: TXLabel
    Left = 190
    Top = 60
    Width = 521
    Height = 51
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Autosize = False
    Caption = 'dCONCEPTE_DESCR'
    Transparent = True
    WordWrap = True
    NoClickMessage = 'Descripci'#243' de concepte'
    NoClick = False
    PassColors = False
    Question = 'Descripci'#243' lliure'
    QHeight = 120
    QWidth = 450
  end
  object dTIPUS_CONCEPTE: TMLabel
    Left = 190
    Top = 110
    Width = 133
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Caption = 'agafant desde articles'
    Transparent = True
    NoClickMessage = 'tipus de concepte'
    OnChangeValue = dTIPUS_CONCEPTEChangeValue
    NoClick = False
    PassColors = False
    Items.Strings = (
      'agafant desde articles'
      'descripci'#243' lliure')
    ItemIndex = 0
  end
  object dID_ELEM: TNLabel
    Left = 400
    Top = 60
    Width = 43
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14413038
    Caption = '(00000)'
    Transparent = True
    NoClickMessage = 'ref. d'#39'article'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    NoClick = True
    PassColors = False
    Format = '(00000)'
    NumType = ntInt
  end
  object Bevel1: TBevel
    Left = 170
    Top = 20
    Width = 2
    Height = 191
    Anchors = [akLeft, akTop, akBottom]
  end
  object dUTS: TNLabel
    Left = 190
    Top = 140
    Width = 24
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = '0,00'
    Transparent = True
    NoClickMessage = 'unitats / hores'
    OnChangeValue = dUTSChangeValue
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    NoClick = False
    PassColors = False
    Question = 'Unitats / hores'
    Format = '0.00'
    NumType = ntFloat
  end
  object dIMPORT: TNLabel
    Left = 190
    Top = 180
    Width = 29
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = '0,00'
    Transparent = True
    NoClickMessage = 'Import total'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    NoClick = True
    PassColors = False
    Question = 'Import total'
    Format = '0.00'
    NumType = ntFloat
  end
  object dLINIA: TULabel
    Left = 190
    Top = 80
    Width = 60
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Caption = 'dID_LINIA'
    Transparent = True
    NoClickMessage = 'l'#237'nia del concepte'
    OnSetInnerCaption = dLINIASetInnerCaption
    NoClick = True
    PassColors = False
  end
  object dID: TNLabel
    Left = 190
    Top = 21
    Width = 9
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = '0'
    Transparent = True
    NoClickMessage = 'Refer'#232'ncia de concepte'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    NoClick = True
    PassColors = False
    Format = '0'
    NumType = ntFloat
  end
  object dID_LIN: TNLabel
    Left = 400
    Top = 80
    Width = 15
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14413038
    Caption = '(0)'
    Transparent = True
    NoClickMessage = 'l'#237'nia del concepte'
    OnChange = dID_LINChange
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    NoClick = True
    PassColors = False
    Format = '(0)'
    NumType = ntInt
  end
  object dID_REF: TNLabel
    Left = 190
    Top = 41
    Width = 55
    Height = 16
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Caption = 'dID_REF'
    Transparent = True
    NoClickMessage = 'Refer'#232'ncia mestre d'#39'aquest concepte'
    NoClick = True
    PassColors = False
    NumType = ntInt
  end
  object dCONCEPTE: TUDBLabel
    Left = 190
    Top = 60
    Width = 82
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Caption = 'dCONCEPTE'
    Transparent = True
    NoClickMessage = 'Descripci'#243' de concepte'
    OnSetInnerCaption = dCONCEPTESetInnerCaption
    NoClick = False
    PassColors = False
    Data.Connection = dm.CG
    Data.Table = 'articles'
    Data.PrimaryKey = 'id'
    Data.SFilterKind = fkProgressive
    Look.FixedRowVAlign = vaTop
    Look.FixedRow = clNavy
    Look.FixedRowHeight = 23
    Look.FixedRowFont.Charset = DEFAULT_CHARSET
    Look.FixedRowFont.Color = clWhite
    Look.FixedRowFont.Height = -12
    Look.FixedRowFont.Name = 'Arial'
    Look.FixedRowFont.Style = []
    Look.Odd = 15002091
    Look.Even = 14673116
    Look.DataRowHeight = 18
    Look.DataFont.Charset = DEFAULT_CHARSET
    Look.DataFont.Color = 10526880
    Look.DataFont.Height = -13
    Look.DataFont.Name = 'Arial'
    Look.DataFont.Style = []
    Look.Border = False
    Look.BorderColor = clBlack
    Look.Focused = 33023
    Look.Selected = clNavy
    Look.BackColor = clBtnFace
    PickStyle = psModalOnePick
    Field = 'descr'
    DerivedFields.Strings = (
      'dID_ELEM=id'
      'dPREU=pvp'
      'dID_LIN=id_lin')
    OnShowPickForm = dCONCEPTEShowPickForm
  end
  object dPREU: TNLabel
    Left = 190
    Top = 160
    Width = 24
    Height = 16
    Cursor = crHandPoint
    ColorMouseOver = 33023
    ColorRestore = clBlack
    Color = 14938354
    Caption = '0,00'
    Transparent = True
    NoClickMessage = 'preu unitari'
    OnChangeValue = dPREUChangeValue
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    NoClick = False
    PassColors = False
    Question = 'Preu unitari'
    Format = '0.00'
    NumType = ntFloat
  end
  object btAnterior: TUText
    Left = 30
    Top = 226
    Width = 111
    Height = 22
    Cursor = crHandPoint
    Alignment = taCenter
    Anchors = [akLeft, akBottom]
    Caption = '&< anterior'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = False
    ReactAndActive = True
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    BorderStyle = sbsSingle
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 8
    TabStop = True
    ParentFont = False
    SelectAndNext = False
    AcceptMouseWheel = True
    PassColor = False
  end
  object btSeguent: TUText
    Left = 140
    Top = 226
    Width = 111
    Height = 22
    Cursor = crHandPoint
    Alignment = taCenter
    Anchors = [akLeft, akBottom]
    Caption = 'seg'#252'ent &>'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = False
    ReactAndActive = True
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    BorderStyle = sbsSingle
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 9
    TabStop = True
    ParentFont = False
    SelectAndNext = False
    AcceptMouseWheel = True
    PassColor = False
  end
  object btEntrar: TUText
    Left = 620
    Top = 226
    Width = 111
    Height = 22
    Cursor = crHandPoint
    Alignment = taCenter
    Anchors = [akRight, akBottom]
    Caption = '&Entrar'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    BorderStyle = sbsSingle
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 10
    TabStop = True
    ParentFont = False
    SelectAndNext = False
    AcceptMouseWheel = True
    PassColor = False
  end
  object tCONCEPTE: TUText
    Left = 30
    Top = 60
    Width = 130
    Height = 19
    Cursor = crHandPoint
    Caption = '&Concepte'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 2
    TabStop = True
    ParentFont = False
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object tPREU: TUText
    Left = 30
    Top = 160
    Width = 130
    Height = 19
    Cursor = crHandPoint
    Caption = '&Preu'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dPREU
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 6
    TabStop = True
    ParentFont = False
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object tUTS: TUText
    Left = 30
    Top = 140
    Width = 130
    Height = 19
    Cursor = crHandPoint
    Caption = '&Unitats / hores'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dUTS
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 5
    TabStop = True
    ParentFont = False
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object tNouArticle: TUText
    Left = 50
    Top = 80
    Width = 111
    Height = 19
    Cursor = crHandPoint
    Caption = '&1. Nou article'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    OnReact = tNouArticleReact
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 3
    TabStop = True
    ParentFont = False
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object tTIPUS_CONCEPTE: TUText
    Left = 30
    Top = 110
    Width = 130
    Height = 19
    Cursor = crHandPoint
    Caption = '&Tipus de concepte'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dTIPUS_CONCEPTE
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 4
    TabStop = True
    ParentFont = False
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UText1: TUText
    Left = 30
    Top = 20
    Width = 130
    Height = 19
    Cursor = crHandPoint
    Caption = 'Ref.'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dID
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 0
    TabStop = True
    ParentFont = False
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object tRefLligada: TUText
    Left = 30
    Top = 40
    Width = 130
    Height = 19
    Cursor = crHandPoint
    Caption = 'Ref. de lligament'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dID_REF
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 1
    TabStop = True
    ParentFont = False
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object tImport: TUText
    Left = 30
    Top = 180
    Width = 130
    Height = 19
    Cursor = crHandPoint
    Caption = 'Import'
    ActLikeLabel = False
    Rounded = False
    DefaultReact = True
    ReactAndActive = False
    LinkedControl = dIMPORT
    TextStyleDefault.Color = clBtnFace
    TextStyleDefault.Font.Charset = DEFAULT_CHARSET
    TextStyleDefault.Font.Color = clWindowText
    TextStyleDefault.Font.Height = -13
    TextStyleDefault.Font.Name = 'MS Sans Serif'
    TextStyleDefault.Font.Style = []
    TextStyleSelected.Color = clSilver
    TextStyleSelected.Font.Charset = DEFAULT_CHARSET
    TextStyleSelected.Font.Color = clBlack
    TextStyleSelected.Font.Height = -13
    TextStyleSelected.Font.Name = 'MS Sans Serif'
    TextStyleSelected.Font.Style = []
    TextStyleMouseOver.Color = clWhite
    TextStyleMouseOver.Font.Charset = DEFAULT_CHARSET
    TextStyleMouseOver.Font.Color = clBlack
    TextStyleMouseOver.Font.Height = -13
    TextStyleMouseOver.Font.Name = 'MS Sans Serif'
    TextStyleMouseOver.Font.Style = []
    Transparent = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    TabOrder = 7
    TabStop = True
    ParentFont = False
    SelectAndNext = True
    AcceptMouseWheel = True
    PassColor = False
  end
  object UDBAlterForm: TUDBAlterForm
    NextButton = btSeguent
    PriorButton = btAnterior
    OkButton = btEntrar
    ControlPrefix = 'd'
    NotAllowPost = False
    AfterLoadValues = UDBAlterFormAfterLoadValues
    OnBeforePost = UDBAlterFormBeforePost
    OnGetNewId = UDBAlterFormGetNewId
    LoadDefValues = UDBAlterFormLoadDefValues
    Messages.ErrorMsg = 'Error actualitzant valors'
    Messages.SaveMsg = 'Guardar canvis?'
    Messages.BadValue = 'Valor '#39'%VALUE%'#39' no v'#224'lid per el camp %FIELD%'
    Messages.DeleteMsg = 'Eliminar concepte?'
    Messages.NotAllowPost = 'Posting not allowed'
    PrimaryField = 'id'
    Left = 550
    Top = 60
  end
end
